[package]
name = "notmouse"
description = "Keyboard-first interaction layer for Linux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
notmouse-core = { path = "../notmouse-core" }
evdev = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs-next = "2.0"

[lints]
workspace = true
