[package]
name = "notmouse"
description = "Keyboard-first interaction layer for Linux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
notmouse-core = { path = "../notmouse-core" }

[lints]
workspace = true
